x-customizable-image: &customizable-image
  image: "frappe/erpnext:v15.36.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/ubuntu/docker/frappe_docker/atlas.conf:/etc/nginx/conf.d/atlas.conf:ro
      - /home/ubuntu/docker/frappe_docker/invictus.conf:/etc/nginx/conf.d/invictus.conf:ro
      - /home/ubuntu/docker/frappe_docker/attendance.conf:/etc/nginx/conf.d/attendance.conf:ro
      - /home/ubuntu/docker/frappe_docker/dashboard.conf:/etc/nginx/conf.d/dashboard.conf:ro
      - /home/ubuntu/docker/frappe_docker/bjj.conf:/etc/nginx/conf.d/bjj.conf:ro
      - ./cert/invictus.powermental.online.pem:/etc/ssl/cloudflare/cloudflare-origin.crt:ro
      - ./cert/invictus.powermental.online.key:/etc/ssl/cloudflare/cloudflare-origin.key:ro
      - ./cert/attendance.powermental.online.pem:/etc/ssl/cloudflare/attendance.powermental.online.crt:ro
      - ./cert/attendance.powermental.online.key:/etc/ssl/cloudflare/attendance.powermental.online.key:ro
      - ./cert/atlas.powermental.online.pem:/etc/ssl/cloudflare/atlas.powermental.online.crt:ro
      - ./cert/atlas.powermental.online.key:/etc/ssl/cloudflare/atlas.powermental.online.key:ro
      - ./cert/dashboard.powermental.online.pem:/etc/ssl/cloudflare/dashboard.powermental.online.crt:ro
      - ./cert/dashboard.powermental.online.key:/etc/ssl/cloudflare/dashboard.powermental.online.key:ro
      - ./cert/wildcard.powermental.online.pem:/etc/ssl/cloudflare/wildcard.powermental.online.crt:ro
      - ./cert/wildcard.powermental.online.key:/etc/ssl/cloudflare/wildcard.powermental.online.key:ro
    restart: always
    ports:
      - "80:80"
      - "443:443"

  bjj-app:
    build: /home/ubuntu/docker/bjj-app
    image: bjj-app
    container_name: bjj-app
    restart: always
    environment:
      - TZ=America/Paramaribo
    volumes:
      - bjj-config:/app/config
      - bjj-data:/app/data

  dashboard:
    build: /home/ubuntu/docker/dashboard
    restart: always
    environment:
      - TZ=America/Paramaribo
    env_file:
      - /home/ubuntu/docker/dashboard/.env

  atlas:
    image: atlas
    restart: always
    environment:
      - TZ=America/Paramaribo

  attendance:
    image: attendance
    build: /home/ubuntu/docker/attendance
    restart: always
    environment:
      - TZ=America/Paramaribo

  backend:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  configurator:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host //empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache //empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue //empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default frontend;

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    <<: *customizable-image
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-long:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data

  scheduler:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    <<: *customizable-image
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  redis-cache-data:
  sites:
  logs:
  bjj-config:
  bjj-data:
